name: CI

on: [push, pull_request]

jobs:
    install-dependencies:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: install modules
              uses: ./.github/actions/module-ci

    lint:
        needs: install-dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Cached Dependencies
              uses: actions/cache@v4
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
            - name: Lint
              run: npm run ci:lint

    test:
        needs: install-dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Cached Dependencies
              uses: actions/cache@v4
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

            - name: Test
              run: npm run ci:test
