name: 'module-ci'
description: 'install node_modules and cache them for later use'
runs:
  using: composite
  steps:
    - name: Cache node modules
      id: cache-modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: ${{ steps.cache-modules.outputs.cache-hit != 'true' }}
      run: npm ci
      shell: bash
